-- Table structure for table `reviews`
CREATE TABLE IF NOT EXISTS public.reviews (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_date timestamp with time zone NOT NULL DEFAULT now(),
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id)
);

-- Create relationship between `reviews` and `inventory` tables
ALTER TABLE IF EXISTS public.reviews
ADD CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

-- Create relationship between `reviews` and `account` tables
ALTER TABLE IF EXISTS public.reviews
ADD CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;